// Package emit produces human-readable artifacts from structured records.
//
// For MVP, it generates a deterministic vault note in Obsidian-compatible
// markdown format. No LLM calls — pure template rendering.
package emit

import (
	"fmt"
	"strings"
	"time"

	"github.com/cyperx84/content-breakdown/internal/schema"
)

// VaultNote renders a SourceRecord + ExtractionRecord + LensResult
// into an Obsidian-compatible markdown note.
func VaultNote(src *schema.SourceRecord, ext *schema.ExtractionRecord, lens *schema.LensResult) string {
	var b strings.Builder

	// Frontmatter
	b.WriteString("---\n")
	fmt.Fprintf(&b, "title: %s Breakdown\n", src.Title)
	fmt.Fprintf(&b, "created: %s\n", time.Now().Format("2006-01-02"))
	fmt.Fprintf(&b, "tags: [breakdown, %s]\n", lens.LensID)
	fmt.Fprintf(&b, "source: %s\n", src.CanonicalURL)
	fmt.Fprintf(&b, "lens: %s\n", lens.LensID)
	fmt.Fprintf(&b, "relevance: %.2f\n", lens.RelevanceScore)
	b.WriteString("---\n\n")

	// Title
	fmt.Fprintf(&b, "# %s — Breakdown\n\n", src.Title)

	// Source section
	b.WriteString("## Source\n\n")
	fmt.Fprintf(&b, "- **Title:** %s\n", src.Title)
	fmt.Fprintf(&b, "- **URL:** %s\n", src.CanonicalURL)
	fmt.Fprintf(&b, "- **Author:** %s\n", src.Author)
	fmt.Fprintf(&b, "- **Extracted:** %s\n", src.Metadata.ExtractedAt.Format("2006-01-02 15:04"))
	fmt.Fprintf(&b, "- **Lens:** %s\n\n", lens.LensID)

	// Summary
	b.WriteString("## Summary\n\n")
	b.WriteString(ext.Summary)
	b.WriteString("\n\n")

	// Tools and patterns
	if len(ext.Tools) > 0 {
		b.WriteString("## Tools & Patterns Mentioned\n\n")
		for _, t := range ext.Tools {
			fmt.Fprintf(&b, "- %s\n", t)
		}
		b.WriteString("\n")
	}

	if len(ext.Workflows) > 0 {
		b.WriteString("## Workflows\n\n")
		for _, w := range ext.Workflows {
			fmt.Fprintf(&b, "- %s\n", w)
		}
		b.WriteString("\n")
	}

	// Lens section
	fmt.Fprintf(&b, "## What Matters for %s\n\n", lensName(lens.LensID))
	b.WriteString(lens.Rationale)
	b.WriteString("\n\n")

	// Ranked ideas
	if len(lens.RankedIdeas) > 0 {
		b.WriteString("## Ranked Ideas\n\n")
		for i, idea := range lens.RankedIdeas {
			fmt.Fprintf(&b, "### %d. %s\n", i+1, idea.Title)
			fmt.Fprintf(&b, "**Score:** %.1f\n\n", idea.Score)
			if idea.WhyItMatters != "" {
				fmt.Fprintf(&b, "**Why it matters:** %s\n\n", idea.WhyItMatters)
			}
			if idea.ImplementationFit != "" {
				fmt.Fprintf(&b, "**Implementation fit:** %s\n\n", idea.ImplementationFit)
			}
		}
	}

	// Opportunities
	if len(ext.Opportunities) > 0 {
		b.WriteString("## Opportunities\n\n")
		for _, o := range ext.Opportunities {
			fmt.Fprintf(&b, "- %s\n", o)
		}
		b.WriteString("\n")
	}

	// Recommended next steps
	if len(lens.RecommendedArtifacts) > 0 {
		b.WriteString("## Recommended Next Steps\n\n")
		for _, a := range lens.RecommendedArtifacts {
			fmt.Fprintf(&b, "- %s\n", a)
		}
		b.WriteString("\n")
	}

	// Provenance footer
	b.WriteString("---\n")
	fmt.Fprintf(&b, "*Generated by breakdown CLI | Source: %s | Lens: %s | Relevance: %.2f*\n",
		src.CanonicalURL, lens.LensID, lens.RelevanceScore)

	return b.String()
}

func lensName(id string) string {
	names := map[string]string{
		"openclaw-product":     "OpenClaw Product",
		"personal-os":          "Personal OS",
		"tooling-worth-stealing": "Tooling Worth Stealing",
	}
	if n, ok := names[id]; ok {
		return n
	}
	return id
}
